# fly.toml app configuration file generated for changedetection-io-hqxxnq on 2024-11-06T16:47:41Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'changedetection-io-hqxxnq'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
